"""Reading an index written as an array of C structs.

The other half of tests/test_toc.py. That one covers the shape a modern
serializer emits, where every name carries its own length. This one covers the
shape that predates it: a name in a fixed-width character field, NUL-padded,
followed by integers, repeated at a constant stride with nothing marking where a
record begins.

The stride is what marks it. Hundreds of name-like fields at one exact spacing
is not something a chance arrangement of bytes produces, and unlike a length
prefix it can be measured. Three things then have to be discovered rather than
assumed, because the shipped archives disagree about all three:

    Quake / Quake II / Hexen II  .pak    stride  64, name at +0  width 56
    Duke Nukem 3D / Shadow Warrior .grp  stride  16, name at +0  width 12
    Half-Life                    .wad3   stride  32, name at +16 width 16
    Doom                         .wad    stride  16, name at +8  width  8

The builders below are those four layouts. They are written from the format
rather than from the detector, so a test passing means the detector reads what
the format actually writes -- if these were generated by asking the detector
what it wanted, the suite would be a mirror.
"""

import io
import os
import random
import struct

import pytest

from acidcat.core.forensics import toc


# ── the four layouts, built as the formats define them ──────────────

def pak(names, payloads, junk_after=b""):
    """Quake: header, payloads, then name-first records with offset and size."""
    body = b"".join(payloads)
    head = 12
    entries = b""
    at = head
    for nm, pl in zip(names, payloads):
        entries += nm.encode().ljust(56, b"\0")
        entries += struct.pack("<ii", at, len(pl))
        at += len(pl)
    blob = struct.pack("<4sii", b"PACK", head + len(body) + len(junk_after),
                       len(entries))
    return blob + body + junk_after + entries


def grp(names, payloads):
    """Duke Nukem: header, name-first records with a SIZE only, then payloads.

    No offsets anywhere in the file -- where a payload lives is implied by
    everything in front of it.
    """
    out = b"KenSilverman" + struct.pack("<i", len(names))
    for nm, pl in zip(names, payloads):
        out += nm.encode().ljust(12, b"\0") + struct.pack("<i", len(pl))
    return out + b"".join(payloads)


def wad(names, payloads, magic=b"IWAD"):
    """Doom: header, payloads, then records with the name LAST, behind the ints."""
    body = b"".join(payloads)
    at = 12
    entries = b""
    for nm, pl in zip(names, payloads):
        entries += struct.pack("<ii", at, len(pl)) + nm.encode().ljust(8, b"\0")
        at += len(pl)
    return (struct.pack("<4sii", magic, len(names), 12 + len(body))
            + body + entries)


def wad3(names, payloads):
    """Half-Life: like Doom but a 32-byte record, name last at +16."""
    body = b"".join(payloads)
    at = 12
    entries = b""
    for nm, pl in zip(names, payloads):
        entries += struct.pack("<iiiBBH16s", at, len(pl), len(pl), 0, 0, 0,
                               nm.encode().ljust(16, b"\0"))
        at += len(pl)
    return (struct.pack("<4sii", b"WAD3", len(names), 12 + len(body))
            + body + entries)


def riffs(n):
    """Payloads a placement can actually be checked against.

    Varied in content AND in length, neither of which is fussiness. An earlier
    version gave every payload the same 64 bytes of a single repeated byte, and
    that fixture built its own table: identical lengths put the payloads on a
    perfect 64-byte grid, and `RIFF` followed by a length byte and NULs reads as
    a NUL-terminated name. The payload area became a stride chain indexing
    nothing, and the tests were measuring the fixture. Real payloads are neither
    uniform in size nor built from one byte.
    """
    out = []
    for i in range(n):
        size = 48 + (i * 13) % 96
        out.append(b"RIFF" + struct.pack("<I", size - 8) + b"WAVE"
                   + bytes((i * 31 + k * 17 + 7) % 256 for k in range(size - 12)))
    return out


NAMES40 = ["sound/hit%02d.wav" % i for i in range(40)]
SHORT40 = ["HIT%02d.wav" % i for i in range(40)]
LUMPS40 = ["DSHIT%02d" % i for i in range(40)]


def read(blob):
    return toc.read_toc(io.BytesIO(blob))


# ── each layout is read, and read correctly ─────────────────────────

class TestTheFourLayouts:
    def test_name_first_with_offsets(self):
        got = read(pak(NAMES40, riffs(40)))
        assert got is not None, "a Quake-shaped directory went unread"
        tc, entries, field, verified, checked = got
        assert tc["shape"] == "fixed-width"
        assert tc["stride"] == 64 and tc["name_width"] == 56
        assert tc["assoc"] == "after"
        assert [e["name"] for e in entries] == NAMES40
        assert tc["placement"] == "absolute"
        assert verified == checked == 40

    def test_name_first_with_sizes_only(self):
        """Duke Nukem stores no offsets at all, so they have to be derived."""
        got = read(grp(SHORT40, riffs(40)))
        assert got is not None
        tc, entries, field, verified, checked = got
        assert tc["stride"] == 16 and tc["name_width"] == 12
        assert tc["placement"] == "contiguous"
        assert [e["name"] for e in entries] == SHORT40
        assert verified == checked == 40

    def test_name_last(self):
        """Doom puts the integers first. Reading them as the NEXT record's is
        the failure this has to avoid, and it is invisible in the names."""
        got = read(wad(LUMPS40, riffs(40)))
        assert got is not None
        tc, entries, field, verified, checked = got
        assert tc["stride"] == 16 and tc["name_width"] == 8
        assert tc["assoc"] == "before", "read the fields off the wrong record"
        assert [e["name"] for e in entries] == LUMPS40

    def test_name_last_in_a_wider_record(self):
        got = read(wad3(LUMPS40, riffs(40)))
        assert got is not None
        tc, entries, _f, _v, _c = got
        assert tc["stride"] == 32 and tc["name_width"] == 16
        assert [e["name"] for e in entries] == LUMPS40

    def test_the_offsets_point_at_the_payloads(self):
        """The whole point. Names without correct extents are a listing, not a
        way into the audio."""
        payloads = riffs(40)
        blob = pak(NAMES40, payloads)
        _tc, entries, _f, _v, _c = read(blob)
        for e, want in zip(entries, payloads):
            assert blob[e["offset"]:e["offset"] + e["length"]] == want


# ── what the shipped archives actually contain ──────────────────────

class TestWhatShippedArchivesDoToIt:
    def test_a_field_that_was_never_zeroed(self):
        """Entry 266 of Quake's PAK0.PAK is

            progs.dat\\x00A\\x00\\x86\\x00\\x00\\x00\\x10E\\xfaw...

        a nine-byte name in a 56-byte struct that still held whatever was on the
        stack, shipped that way in 1996. Requiring clean padding is stricter
        than the format, and it threw away a 339-entry directory over one
        record.
        """
        names = list(NAMES40)
        blob = bytearray(pak(names, riffs(40)))
        at = blob.index(b"sound/hit07.wav")
        junk = b"\x00A\x00\x86\x00\x00\x00\x10E\xfaw\xa2\xc1\xf6w"
        blob[at + 16:at + 16 + len(junk)] = junk
        got = read(bytes(blob))
        assert got is not None, "one dirty field lost the whole directory"
        _tc, entries, _f, _v, _c = got
        assert len(entries) == 40
        assert entries[7]["name"] == "sound/hit07.wav"

    def test_a_name_that_fills_its_field(self):
        """123 of the 456 names in DUKE3D.GRP are exactly twelve characters, so
        they carry no NUL at all. Anchoring the chain on padding is right;
        requiring it of every record cuts the directory into fragments."""
        names = ["DUKETEAM.ANM"] * 1 + ["TILES%03d.ART" % i for i in range(20)]
        names = [n[:12] for n in names] + SHORT40
        got = read(grp(names, riffs(len(names))))
        assert got is not None
        _tc, entries, _f, _v, _c = got
        assert [e["name"] for e in entries] == names

    def test_padding_that_is_not_packing(self):
        """freedoom pads every lump up to a four-byte boundary, so
        offset+size == next_offset holds for barely half its entries -- its real
        directory scores 0.601. An index is not required to pack its payloads,
        only to not overlap them."""
        payloads = [b"RIFF" + struct.pack("<I", 54) + b"WAVE" + b"\x11" * 50
                    for _ in range(40)]
        padded = [p + b"\x00" * 2 for p in payloads]      # 4-byte alignment
        body = b"".join(padded)
        at, entries = 12, b""
        for nm, p in zip(LUMPS40, padded):
            entries += struct.pack("<ii", at, len(p) - 2) + nm.encode().ljust(8, b"\0")
            at += len(p)
        blob = (struct.pack("<4sii", b"IWAD", 40, 12 + len(body))
                + body + entries)
        got = read(blob)
        assert got is not None, "an aligned archive is still an archive"
        tc, ents, field, _v, _c = got
        # placed, not merely found: a lump name carries no extension, so no
        # magic can confirm it and the arithmetic is the ONLY evidence there is
        assert field is not None, "found the index and could not follow it"
        assert tc["placement"] == "absolute"
        assert len(ents) == 40
        for e, want in zip(ents, payloads):
            assert blob[e["offset"]:e["offset"] + e["length"]] == want

    def test_a_first_record_whose_run_starts_early(self):
        """Entry 0 of Quake II's directory is a perfectly good name whose
        printable run begins six bytes before it, inside the payload in front.
        The run therefore does not START on the record grid, so the record is
        not a NUL-terminated anchor -- and a walk that reports the last ANCHORED
        position rather than the last record-shaped one drops it. One entry in
        3,307, and no other symptom.
        """
        # the printable bytes must be the LAST thing before the directory,
        # which is the whole mechanism: the run then straddles the boundary
        tail = b"RIFF" + struct.pack("<I", 56) + b"WAVE" + b"\x11" * 43 + b"wkW[S"
        blob = pak(NAMES40, riffs(39) + [tail])
        got = read(blob)
        assert got is not None
        _tc, entries, _f, _v, _c = got
        assert entries[0]["name"] == NAMES40[0], \
            "lost the first record for not being NUL-terminated"
        assert len(entries) == 40

    def test_records_in_front_of_the_index(self):
        """The bytes before a directory keep looking like records -- for
        eighteen of them in freedoom1.wad. Nothing has to be searched: an
        archive that writes payloads first has its last payload end exactly
        where the index begins."""
        decoy = b"".join(struct.pack("<ii", 900 + i, 40) + b"DECOY%03d" % i
                         for i in range(18))
        blob = wad(LUMPS40, riffs(39) + [decoy])
        got = read(blob)
        assert got is not None
        _tc, entries, _f, _v, _c = got
        assert [e["name"] for e in entries] == LUMPS40, \
            "the index was taken to start inside the payload in front of it"


# ── the ways a wrong answer gets produced ───────────────────────────

class TestItPrefersTheRightReadingOfTheSameBytes:
    def test_a_doubled_stride_does_not_win(self):
        """Any table can be read at twice its stride, giving a perfectly
        self-consistent table of every other record. Quake's 339-entry
        directory lost to a 169-entry reading of itself."""
        got = read(pak(NAMES40, riffs(40)))
        _tc, entries, _f, _v, _c = got
        assert len(entries) == 40, "read every other record and called it a table"

    def test_only_one_reading_of_a_stretch_of_bytes_survives(self):
        """Tested on the function, because the shape that makes it matter needs
        a real archive to produce. Dropping it costs SW.GRP its directory
        entirely -- 2,211 unplaceable entries instead of 693 -- because the
        rival readings of one region crowd out every other candidate. The rule
        is that a region gets one reading, and it is the one accounting for the
        most records.
        """
        def table(offset, n, stride):
            return {"entries": [{"offset": offset + i * stride,
                                 "end": offset + (i + 1) * stride,
                                 "name": "n%03d" % i, "fields": [0],
                                 "name_at": offset + i * stride}
                                for i in range(n)],
                    "offset": offset, "stride": stride, "uniq": 1.0,
                    "padded": 1.0, "pairing": 0.0}

        fine = table(1000, 40, 64)          # the same bytes read two ways
        coarse = table(1000, 20, 128)
        far = table(90000, 30, 64)          # a different region entirely
        kept = toc._one_per_region([coarse, fine, far])
        assert far in kept, "dropped a table that overlapped nothing"
        assert fine in kept and coarse not in kept, \
            "kept the reading that accounts for half the records"

    def test_no_two_candidates_describe_the_same_bytes(self):
        """The invariant at the call site, not just in the function. Every table
        can be read at a multiple of its stride, so without this the list fills
        with rival readings of one region -- which is how SW.GRP came back with
        2,211 unplaceable entries in place of its 693-entry directory."""
        cands = toc.fixed_candidates(pak(NAMES40, riffs(40)), toc._MIN_ENTRIES)
        spans = sorted((t["offset"], t["entries"][-1]["end"]) for t in cands)
        for (a_lo, a_hi), (b_lo, b_hi) in zip(spans, spans[1:]):
            assert b_lo >= a_hi, (
                f"two candidates cover the same bytes: "
                f"0x{a_lo:x}..0x{a_hi:x} and 0x{b_lo:x}..0x{b_hi:x}")

    def test_a_chain_spanning_two_field_widths(self):
        """A stride chain does not always cover one population. Where it runs
        from a directory into records of a different shape on the same grid, the
        votes split between two real widths and whichever leads by one wins --
        so a single dirty field decides which. Both have to be tried.

        Here a block of 8-byte-name records sits on the same 64-byte grid as a
        56-byte-name directory, and the wrong choice reads the directory's names
        as their first eight characters.
        """
        decoy = b"".join(("TG%03d" % i).encode().ljust(8, b"\0")
                         + bytes(0x80 | ((i * 29 + k) % 128) for k in range(56))
                         for i in range(70))
        blob = pak(NAMES40, riffs(39) + [decoy])
        # the decoy must actually outvote the directory, or the two readings are
        # not in competition and this passes without testing anything
        counts = {}
        for chain, stride in toc._stride_chains(blob, toc._MIN_ENTRIES):
            if stride != 64:
                continue
            for p in chain:
                w = toc._padded_width(blob, p, 60)
                if w:
                    counts[w] = counts.get(w, 0) + 1
        assert counts.get(8, 0) > counts.get(56, 0), (
            f"the wrong width does not lead the vote here: {counts}")

        got = read(blob)
        assert got is not None
        tc, entries, _f, _v, _c = got
        assert tc["name_width"] == 56, tc["name_width"]
        assert [e["name"] for e in entries] == NAMES40

    def test_the_width_is_the_common_one_not_the_smallest(self):
        """A character field is a fixed size hundreds of records agree on, but
        one record's measurement can come up short. Taking the minimum let a
        single dirty field redefine a 56-byte field as a 10-byte one."""
        blob = bytearray(pak(NAMES40, riffs(40)))
        at = blob.index(b"sound/hit11.wav")
        blob[at + 10] = 0x86                    # ends the run early, no padding
        got = read(bytes(blob))
        assert got is not None
        tc, _e, _f, _v, _c = got
        assert tc["name_width"] == 56, tc["name_width"]

    def test_chains_are_ranked_by_padding_and_not_by_length(self):
        """Validating a chain costs a regex match per record, so only the most
        promising are validated -- and what "promising" means decided whether
        DUKE3D.GRP could be read at all. Ordered by raw length its real
        459-record directory sat below eighty longer chains of texture data and
        was cut before anything looked at it.

        Reproducing 42 MB of texture here is not possible, so the ordering is
        tested on its own terms: a short densely-padded chain against a long
        sparsely-padded one, which is the shape of that collision.
        """
        dense = b"".join(("dense/name%03d.wav" % i).encode().ljust(60, b"\0")
                         + bytes([0xF0, i % 251, 0xF1, 0xF2])
                         for i in range(60))
        sparse = b"".join(
            (("sparse%03d" % i).encode().ljust(28, b"\0")
             if i % 4 == 0 else ("sparsename%03dxyzpqrstuvwxyzA" % i).encode())
            + bytes([0xF0, 0xF3, 0xF4, i % 251])
            for i in range(200))
        blob = b"\xee" * 64 + dense + b"\xee" * 64 + sparse
        at_dense, at_sparse = 64, 64 + len(dense) + 64

        chains = toc._stride_chains(blob, toc._MIN_ENTRIES)
        assert chains, "no chains at all, so this measures nothing"
        head = chains[0][0]
        longest = max(chains, key=lambda cs: len(cs[0]))[0]
        assert len(longest) > len(head), (
            "the sparse block is not longer than the dense one, so ordering by "
            "length and ordering by padding cannot be told apart here")
        assert at_dense <= head[0] < at_sparse, (
            "the chain with the most NUL-terminated names is not first; it "
            f"starts at 0x{head[0]:x}")


class TestItDoesNotInventTables:
    """A wrong table is worse than no table: it is a confident answer with a
    filename attached. Measured against 1,200 real audio files this reported no
    placed table at all, and these are the shapes that make that non-trivial."""

    def test_random_bytes(self):
        random.seed(9)
        assert toc.find_fixed_toc(
            bytes(random.randrange(256) for _ in range(200000))) is None

    def test_a_wall_texture(self):
        """The specimen that produced a confident false positive from the other
        detector -- real bytes, not a ramp written here."""
        p = os.path.join(os.path.dirname(__file__), "..", "data", "fixtures",
                         "toc-false-positive.bin")
        with open(p, "rb") as fh:
            assert toc.find_fixed_toc(fh.read()) is None

    def test_a_smooth_ramp(self):
        assert toc.find_fixed_toc(bytes((i * 7) % 256
                                        for i in range(200000))) is None

    def test_digital_silence(self):
        assert toc.find_fixed_toc(b"\x00" * 300000) is None

    def test_prose(self):
        data = (b"The quick brown fox. See readme.txt and notes.md too. ") * 3000
        assert toc.find_fixed_toc(data) is None

    def _fake_table(self, name_for, width=20, n=60):
        """A perfectly regular table whose names are the thing in question."""
        recs = b""
        for i in range(n):
            recs += name_for(i).ljust(width, b"\0") + struct.pack("<iii",
                                                                  i * 100, 80, 0)
        return b"\xee" * 64 + recs

    def test_names_that_are_mostly_punctuation(self):
        """The original defect in the other detector was a wall texture whose
        "names" were 39% alphanumeric, the rest the punctuation that sits beside
        the letters in ASCII. Nothing about stride or padding rejects that -- a
        run of graphics is as regular as a directory -- so the names themselves
        have to be held to looking like names."""
        blob = self._fake_table(lambda i: ("[^_`%d]^_`" % i).encode())
        assert toc.find_fixed_toc(blob) is None

    def test_names_that_are_all_the_same(self):
        """A real index names distinct things. Smooth data chained at a constant
        stride produces the same few near-identical runs over and over, and this
        is what separates them: measured over 300 real audio files, dropping it
        took the number reporting a table from 4 to 27."""
        blob = self._fake_table(lambda i: b"aaaa")
        assert toc.find_fixed_toc(blob) is None

    def test_names_that_never_end(self):
        """NUL padding is the half of the evidence that smooth bytes cannot
        fake, because 0x00 is nowhere near printable ASCII. A table where no
        name ever terminates is a block of text, and treating it as an index
        means inventing entries out of prose or code.

        Rejected before a table is ever built rather than by a floor afterwards:
        a chain is only proposed from four consecutive NUL-terminated names, so
        data with none proposes nothing. The floor that used to sit at the end
        was measured and rejected nothing here or over 300 real audio files, and
        was removed rather than left standing as a defence that never fires.
        """
        names = [("run%02dofsolidtextabcd" % i).encode()[:20] for i in range(60)]
        assert all(len(nm) == 20 for nm in names), \
            "these must FILL the field, or they are padded and prove nothing"
        blob = self._fake_table(lambda i: names[i], width=20)
        assert toc.find_fixed_toc(blob) is None

    def test_eight_bit_audio(self):
        """The case that matters most: this exists to find audio inside unknown
        containers, and eight-bit PCM sits squarely in printable ASCII."""
        random.seed(3)
        pcm = bytearray()
        v = 128
        for _ in range(200000):
            v = max(0, min(255, v + random.randrange(-6, 7)))
            pcm.append(v)
        assert toc.find_fixed_toc(bytes(pcm)) is None


# ── honesty of the numbers it reports ───────────────────────────────

class TestTheReportedNumbersAreMeasurements:
    def test_more_entries_than_the_search_budget_are_verified(self):
        """Ranking hypotheses stops reading payloads once it has seen enough.
        If that budget reached the caller, DUKE3D.GRP's 373 verified sounds
        would report "64 of 64" -- a cap wearing the clothes of a result.

        Built as a .grp, because that is where the budget applies: deriving
        contiguous offsets means walking every entry, so the reads are capped,
        while an archive that stores its offsets is checked directly and never
        needed a cap at all.
        """
        n = toc._MAX_CHECKS * 2
        names = ["HIT%04d.wav" % i for i in range(n)]
        tc, _e, _f, verified, checked = read(grp(names, riffs(n)))
        assert tc["placement"] == "contiguous"
        assert checked == n, f"reported {checked}, the search budget is {toc._MAX_CHECKS}"
        assert verified == n, verified

    def test_confidence_never_reaches_a_signature_match(self):
        """A shape, not a magic number. It must never outrank a container whose
        signature actually verified, and those sit at 0.9."""
        names = ["sound/set%02d/hit%03d.wav" % (i // 40, i) for i in range(320)]
        tc, _e, _f, _v, _c = read(pak(names, riffs(320)))
        assert tc["confidence"] <= 0.85

    def test_a_table_it_cannot_follow_is_not_reported_as_no_table(self):
        """"There is an index here and I cannot read where it points" is a
        different answer from "there is no index here". Logic EXS24 instruments
        land here: 17 real zone records whose integers are synth parameters, not
        offsets."""
        names = ["zone/sample%02d.wav" % i for i in range(40)]
        entries = b""
        for i, nm in enumerate(names):
            entries += nm.encode().ljust(56, b"\0")
            entries += struct.pack("<ii", -100663260 + i, 32512)
        got = read(b"\x00" * 64 + entries)
        assert got is not None, "silently dropped a table it did find"
        _tc, ents, field, verified, checked = got
        assert field is None
        assert len(ents) >= 12


def test_the_windows_reach_both_ends_of_a_file():
    """An index is usually written last, because appending payloads and writing
    the directory afterwards means never seeking backwards. Quake, Doom and
    Half-Life all put theirs within 450 KB of the tail, so the head-only window
    this used to get missed most of the family."""
    blob = pak(NAMES40, [b"RIFF" + struct.pack("<I", 4088) + b"WAVE"
                         + bytes([i]) * 4084 for i in range(40)])
    assert len(blob) > 2 << 10
    got = toc.read_toc(io.BytesIO(blob), head=1024, tail=1 << 20)
    assert got is not None, "a directory past the head window went unseen"
    tc, entries, _f, _v, _c = got
    assert tc["window"] == "tail"
    assert len(entries) == 40


def test_real_game_archives():
    """The specimens this was built against, if they are on this machine.

    Ground truth is re-derived from each archive's own header rather than
    written down here, so the test cannot drift into asserting what the detector
    happens to do. Point ACIDCAT_ARCHIVE_CORPUS at a directory of .pak/.grp/.wad
    files -- an environment variable rather than one machine's drive letter,
    which is configuration wearing the clothes of a constant.
    """
    root = os.environ.get("ACIDCAT_ARCHIVE_CORPUS", "")
    if not (root and os.path.isdir(root)):
        pytest.skip("set ACIDCAT_ARCHIVE_CORPUS to a dir of game archives")
    checked = 0
    for dirpath, _dirs, files in os.walk(root):
        for name in sorted(files):
            path = os.path.join(dirpath, name)
            want = _declared_count(path)
            if want is None or want < toc._MIN_ENTRIES:
                continue
            with open(path, "rb") as fh:
                got = toc.read_toc(fh)
            assert got is not None, f"{name}: no table found"
            _tc, entries, _f, _v, _c = got
            assert len(entries) == want, \
                f"{name}: read {len(entries)} of {want} entries"
            checked += 1
    if not checked:
        pytest.skip("no archive with a parseable header under that directory")


def _declared_count(path):
    """How many entries the archive's own header claims, or None."""
    try:
        size = os.path.getsize(path)
        with open(path, "rb") as fh:
            head = fh.read(16)
    except OSError:
        return None
    if len(head) < 16:
        return None
    magic = head[:4]
    if magic == b"PACK":
        _ofs, length = struct.unpack("<ii", head[4:12])
        return length // 64 if 0 < length < size else None
    if magic in (b"IWAD", b"PWAD", b"WAD2", b"WAD3"):
        n, ofs = struct.unpack("<ii", head[4:12])
        rec = 32 if magic == b"WAD3" else 16
        return n if 0 < n and 0 < ofs + n * rec <= size else None
    if head[:12] == b"KenSilverman":
        n = struct.unpack("<i", head[12:16])[0]
        return n if 0 < n and 16 + n * 16 <= size else None
    return None
